services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deep_origin
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/deep_origin
      FRONTEND_BASE_URL: http://localhost:3000
      FRONTEND_NOT_FOUND_URL: http://localhost:3000/not-found
      JWT_SECRET: super-secret-key
      JWT_EXPIRES_IN: 1d
      NODE_ENV: development
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
      
volumes:
  pgdata:
